In [1]:
import torch

In [2]:
torch.__version__

'2.2.1+cu121'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.item()

7

In [5]:
scalar.ndim

0

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
TENSOR = torch.tensor([[[1,2,3],
                        [9,8,7],
                        [4,3,5]]])
TENSOR

tensor([[[1, 2, 3],
         [9, 8, 7],
         [4, 3, 5]]])

In [8]:
TENSOR.ndim

3

In [9]:
TENSOR.shape

torch.Size([1, 3, 3])

In [10]:
TENSOR[0,2]

tensor([4, 3, 5])

In [11]:
#Random tensors

rTensors = torch.rand(3,4)

In [12]:
rTensors.ndim

2

In [13]:
# Random like image
image = torch.rand(3,224,224)
image.shape ,image.ndim

(torch.Size([3, 224, 224]), 3)

In [14]:
#zeros and ones
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones((3,4))

In [16]:
ones.dtype

torch.float32

In [17]:
## range of tensors

zero_ten = torch.arange(0,10,step = 2)
zero_ten

tensor([0, 2, 4, 6, 8])

In [18]:
# tenors like

ten_zero = torch.zeros_like(zero_ten)
ten_zero

tensor([0, 0, 0, 0, 0])

In [19]:
float_32_tensor = torch.tensor([2, 3, 4],
                               dtype=torch.float32,
                               device='cpu',
                               requires_grad=False)
float_32_tensor

tensor([2., 3., 4.])

In [20]:
float_32_tensor.dtype

torch.float32

In [21]:
float_16_tensor = float_32_tensor.type(torch.int16)

In [22]:
float_16_tensor

tensor([2, 3, 4], dtype=torch.int16)

In [23]:
## Tensors OP

# torch.mul()
# torch.add()
# torch.multiply()

In [24]:
# matrix multiplication

torch.matmul(zero_ten,ten_zero)

tensor(0)

In [25]:
# Min

x = torch.arange(0,100,10)
torch.min(x), torch.argmin(x)

(tensor(0), tensor(0))

In [26]:
# Max

torch.max(x) , torch.argmax(x)

(tensor(90), tensor(9))

In [27]:
# Mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [28]:
# Reshaping, Stacking, Sqeezing, Unsqueezing tensors


x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
x_reshape = x.reshape(1, 9)
x.shape , x_reshape.shape

(torch.Size([9]), torch.Size([1, 9]))

In [30]:
z = x.view(1,9)
z.shape

torch.Size([1, 9])

In [31]:
x_stacked = torch.stack([x,x,x,x],dim=1)

In [32]:
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [33]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
x_squeeze = torch.squeeze(x_reshape)

x_reshape.shape , x_squeeze.shape

(torch.Size([1, 9]), torch.Size([9]))

In [35]:
x_squeeze

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
x_unsq = torch.unsqueeze(x_squeeze,dim=1)
x_unsq.shape

torch.Size([9, 1])

In [37]:
x_unsq

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [38]:
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [39]:
# Reproducibility

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_a = torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
random_b = torch.rand(3,3)

random_a == random_b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [40]:
# Check for GPU access with Pytorch
torch.cuda.is_available()

True

In [41]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [42]:
print(device)

cuda


In [46]:
tensor = torch.rand(4,5)

tensor_gpu  = tensor.to(device)
tensor_gpu

tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
        [0.1447, 0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036, 0.2018]], device='cuda:0')

In [48]:
tensor_gpu.cpu()

tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
        [0.1447, 0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036, 0.2018]])